name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      expo_version:
        description: 'New OneSignal Expo Plugin Version (e.g., 2.1.0 or 2.1.0-beta.1)'
        required: true
        type: string
      target_branch:
        description: 'Target branch to create the release PR on. Defaults to main.'
        required: false
        type: string
        default: main

jobs:
  prep:
    uses: OneSignal/sdk-shared/.github/workflows/prep-release.yml@main
    with:
      target_repo: OneSignal/onesignal-expo-plugin
      version: ${{ inputs.expo_version }}

  # Expo Plugin specific steps
  update_version:
    needs: prep
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # Need repository otherwise caller would set github.repository to the caller itself (e.g. sdk-shared)
          repository: OneSignal/onesignal-expo-plugin
          ref: ${{ needs.prep.outputs.release_branch }}

      - name: Setup Git User
        uses: OneSignal/sdk-shared/.github/actions/setup-git-user@main

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update sdk version
        run: |
          NEW_VERSION="${{ inputs.expo_version }}"

          # Update package.json version
          bun pm pkg set version="$NEW_VERSION"

          # Only commit if there are changes
          git add -A
          git diff --staged --quiet && exit 0
          git commit -m "Release $NEW_VERSION" && git push

  create-pr:
    needs: [prep, update_version]
    uses: OneSignal/sdk-shared/.github/workflows/create-release.yml@main
    with:
      # Need target_repo otherwise caller would set github.repository to the caller itself (e.g. sdk-shared)
      target_repo: OneSignal/onesignal-expo-plugin
      release_branch: ${{ needs.prep.outputs.release_branch }}
      target_branch: ${{ inputs.target_branch }}
